name: vouch
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using pub publish. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: 3.0.0
  barcode_widget: 2.0.3
  cached_network_image: 3.3.1
  cloud_firestore:
  cloud_functions: 4.6.7
  collection: 1.18.0
  dropdown_button2: 2.3.9
  equatable: 2.0.5
  file_picker: 6.1.1
  firebase_analytics: 10.8.8
  firebase_app_check: 0.2.1+16
  firebase_auth:
  firebase_core:
  firebase_crashlytics: 3.4.17
  firebase_dynamic_links: 5.4.16
  firebase_messaging: 14.7.18
  firebase_performance: 0.9.3+16
  firebase_storage: 11.6.8
  flutter_animate: 4.1.1+1
  flutter_barcode_scanner:
    git:
      url: https://github.com/FlutterFlow/flutter_barcode_scanner
  flutter_cache_manager: 3.3.1
  flutter_plugin_android_lifecycle: 2.0.17
  font_awesome_flutter: 10.6.0
  from_css_color: 2.0.0
  go_router: 7.1.1
  google_fonts: 6.1.0
  http: 1.2.0
  image_picker: 1.0.4
  intl: 0.19.0
  json_path: 0.6.2
  lottie: 2.7.0
  mime_type: 1.0.0
  page_transition: 2.1.0
  percent_indicator: 4.2.2
  permission_handler: 10.0.0
  pin_code_fields: 8.0.1
  plugin_platform_interface: 2.1.8
  pointer_interceptor: 0.10.1
  provider: 6.0.5
  rxdart: 0.27.7
  share_plus: 7.2.1
  shared_preferences: 2.2.2
  smooth_page_indicator: 1.1.0
  sqflite: 2.2.6
  stop_watch_timer: 3.0.2
  stream_transform: 2.1.0
  timeago: 3.2.2
  universal_io: 2.2.2
  url_launcher: 6.2.5
  uuid: ^4.0.0
  video_player: 2.8.1
  webview_flutter: 4.7.0
  webviewx_plus: 0.5.0
  xml: 6.3.0
  flutter_contacts: ^1.1.7+1
  flutter_svg: ^2.0.9
  modal_bottom_sheet: ^3.0.0
  get:
  flutter_screenutil: ^5.9.0
  dio:
  pretty_dio_logger:
  intl_phone_number_input: ^0.7.4
  choose_input_chips: ^1.1.3
  dotted_line: ^3.2.2
  skeletonizer: ^1.1.1
  date_time_format: ^2.0.1
  flutter_local_notifications:
  uni_links:
  qr_code_scanner:
  flutter_app_badger:
  app_links:
  connectivity_plus:
  upgrader: ^10.3.0




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  badges: ^3.1.2

dependency_overrides:
  http: 1.2.0
  pointer_interceptor: 0.10.1
  uuid: ^4.0.0

dev_dependencies:
  flutter_launcher_icons: 0.13.1
  flutter_lints: 3.0.0
  image: 4.0.17
  lints: 3.0.0

  flutter_test:
    sdk: flutter


flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  image_path: 'assets/images/app_launcher_icon.png'


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
    - lib/new_code/home_page/paths_screen/paths_screen.dart
  fonts:
    - family: 'Bricolage Grotesque'
      fonts:
        - asset: assets/fonts/BricolageGrotesque_24pt-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/BricolageGrotesque_24pt-Light.ttf
          weight: 300
        - asset: assets/fonts/BricolageGrotesque_24pt-Regular.ttf
        - asset: assets/fonts/BricolageGrotesque_24pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/BricolageGrotesque_24pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/BricolageGrotesque_24pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/BricolageGrotesque_24pt-ExtraBold.ttf
          weight: 800


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages